# Generated by Django 4.0.4 on 2022-05-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'counter'), (3, 'declined'), (4, 'accepted'), (5, 'paid')], max_length=1),
        ),
    ]
