# Generated by Django 4.0.4 on 2022-05-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_condition_remove_auction_tag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.condition'),
            preserve_default=False,
        ),
    ]
