# Generated by Django 4.0.4 on 2022-05-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer_has_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller_has_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
