# Generated by Django 4.0.4 on 2022-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_offer_buyer_has_reviewed_offer_seller_has_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='creation_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
