# Generated by Django 4.0.4 on 2022-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_offer_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
