# Generated by Django 4.0.4 on 2022-05-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='tag',
        ),
        migrations.AddField(
            model_name='auction',
            name='tag',
            field=models.ManyToManyField(to='user.tag'),
        ),
    ]
