# Generated by Django 4.0.4 on 2022-05-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_auction_tag_auction_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='catID',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='locID',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cardinfo',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='provID',
            new_name='prov',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='auctionID',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='RUID',
            new_name='reporter_user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='UID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewedID',
            new_name='reviewed_user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewerID',
            new_name='reviewer_user',
        ),
    ]
