# Generated by Django 4.0.4 on 2022-05-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_report_reported_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
