# Generated by Django 4.0.4 on 2022-05-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='user.user'),
        ),
    ]
