# Generated by Django 4.0.4 on 2022-05-06 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='cvc',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.PositiveIntegerField(choices=[(1, 'user'), (2, 'bug')], max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'sale'), (2, 'purchase')], max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
