# Generated by Django 4.0.4 on 2022-05-06 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_cardinfo_cvc_alter_report_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.PositiveIntegerField(choices=[(1, 'user'), (2, 'bug')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'sale'), (2, 'purchase')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
