# Generated by Django 4.0.4 on 2022-05-06 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_report_report_type_alter_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='card_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
