# Generated by Django 4.0.4 on 2022-05-13 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_country_alter_cardinfo_zip_alter_cardinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='house_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
