# Generated by Django 4.0.4 on 2022-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_cardinfo_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='cardholder_first_name',
            field=models.CharField(default='james bond', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='cardholder_last_name',
            field=models.CharField(default='double-o-seven', max_length=255),
            preserve_default=False,
        ),
    ]
