# Generated by Django 4.0.4 on 2022-05-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_cardinfo_cardholder_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='region',
        ),
    ]
